# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Paradise Lost
url: http://darren123chen.github.io
feed: /atom.xml
author_info: <a href="http://darren123chen.github.io/">DarrenChen</a>

myblog:
  gavatar: images/15123280.jpeg
  gpname: DarrenChen
  linkedin: http://www.linkedin.com/in/chen-jia-5894a1b7
  github: https://github.com/darren123chen
  email: mailto:chenjia2432@icloud.com
  coverimgs: []
  postbgimg: []
  categories: []
categories: [python, books]
